# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: cf2-nostr-image-services

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  architecture: x86_64
  timeout: 29
  #environment:
  #  S3_BUCKET_CF: { Ref: S3Bucket }
  #  S3_BUCKET_CF_URL: { GetAtt: [S3Bucket, DomainName] }
    #S3_BUCKET_CF_URL: { Ref: S3Bucket } ".s3.amazonaws.com"


package:
  individually: true
  patterns:
    - '!serverless.yml'
    - '!serverless-cloudfront.yml'
    - '!variables.sample.yml'
    - '!variables.yml'
  
custom:
  S3_BUCKET: ${file(./variables.yml):S3_BUCKET}
  CF_CUSTOM_DOMAIN: ${file(./variables.yml):CF_CUSTOM_DOMAIN}
  CF_CUSTOM_CERTIFICATE_ARN: ${file(./variables.yml):CF_CUSTOM_CERTIFICATE_ARN}

resources:
  Resources:
    CloudFrontOriginIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: 'origin identity'
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
          
          DistributionConfig:
            DefaultRootObject:  index.html
            Aliases:
              - ${self:custom.CF_CUSTOM_DOMAIN}
            ViewerCertificate:
              AcmCertificateArn: ${self:custom.CF_CUSTOM_CERTIFICATE_ARN}
              SslSupportMethod: sni-only
              MinimumProtocolVersion: TLSv1.2_2021
            PriceClass: PriceClass_100
            Enabled: true
            Origins:
            # PATH /

              - DomainName: !GetAtt S3Bucket.DomainName
                Id: { Ref: S3Bucket }
                S3OriginConfig:

                  OriginAccessIdentity: !Join
                    - ''
                    - - origin-access-identity/cloudfront/
                      - !Ref CloudFrontOriginIdentity
          
            DefaultCacheBehavior:
              TargetOriginId: { Ref: S3Bucket }
              CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
              ViewerProtocolPolicy: redirect-to-https
              
            CacheBehaviors:
              - PathPattern: /images/*
                TargetOriginId: { Ref: S3Bucket }
                CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
                ForwardedValues:
                  QueryString: true
                  Cookies:
                    Forward: none
                AllowedMethods:
                  - GET
                  - HEAD
                  - OPTIONS
                ViewerProtocolPolicy: redirect-to-https
              - PathPattern: /*
                TargetOriginId: { Ref: S3Bucket }
                #CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
                CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
                ForwardedValues:
                  QueryString: true
                  Cookies:
                    Forward: none
                AllowedMethods:
                  - GET
                  - HEAD
                  - OPTIONS
                ViewerProtocolPolicy: redirect-to-https


      
  # create S3 bucket 
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.S3_BUCKET}
        
    S3BucketPolicy: # Allow uploaded files to be public and downloadable
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: { Ref: S3Bucket }
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: 'Allow'
              Resource: { Fn::Join: ['', [{ Fn::GetAtt: [S3Bucket, Arn] }, '/*']] } # arn:aws:s3:::bucketName/*
              Principal: 
                AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
  Outputs:
    S3Bucket:
      Value: { Ref: S3Bucket }
      Export:
        Name: S3Bucket
    CloudFrontDistribution:
      Value: { Ref: CloudFrontDistribution }
      Export:
        Name: CloudFrontDistribution
      # export distribution domain name
    CloudFrontDistributionDomainName:
      Value: !GetAtt CloudFrontDistribution.DomainName
      Export:
        Name: CloudFrontDistributionDomainName
    CloudFrontOriginIdentity:
      Value: { Ref: CloudFrontOriginIdentity }
      Export:
        Name: CloudFrontOriginIdentity
